stages:
  - validate
  - deploy

variables:
  AWS_DEFAULT_REGION: "ap-southeast-1"
  STACK_NAME: "EKS-DB-Stack"
  TEMPLATE_FILE: "create-infra.yaml"
  KEY_NAME: "zh-aws-12Sep2021"
  PUBLIC_SUBNET_ID: "subnet-2010b868"
  PRIVATE_SUBNET_ID: "subnet-086a3dc81dd7e1b5f"
  VPC_ID: "vpc-a932e5cf"

validate:
  stage: validate
  tags:
    - g-docker-only
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - |
      #!/bin/sh
      aws cloudformation validate-template --template-body file://$TEMPLATE_FILE

deploy:
  stage: deploy
  tags:
    - g-docker-only
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - |
      #!/bin/sh
      aws cloudformation deploy \
        --stack-name $STACK_NAME \
        --template-file $TEMPLATE_FILE \
        --capabilities CAPABILITY_IAM \
        --parameter-overrides \
          KeyName=$KEY_NAME \
          PublicSubnetId=$PUBLIC_SUBNET_ID \
          PrivateSubnetId=$PRIVATE_SUBNET_ID \
          VpcId=$VPC_ID \
          MongoDBUsername=$MONGODB_USERNAME \
          MongoDBPassword=$MONGODB_PASSWORD
      
      echo "Deployment complete. Outputs:"
      aws cloudformation describe-stacks \
        --stack-name $STACK_NAME \
        --query "Stacks[0].Outputs" \
        --output table